### ISSUE TITLE
Whole page should display in a container (transactions should be in the middle)

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity-sysui-app#8]
Container width around 800px. Now it looks shitty on large screens:
![screenshot from 2016-06-21 17 12 46](https://cloud.githubusercontent.com/assets/581548/16234962/63e56f90-37d3-11e6-86a4-6a8c310cf107.png)

**Comment by goldylucks** [comment]
not sure about the topbar

if we should center the background color, the text, or none

**Comment by tomusdrw** [comment]
Just the text imho
